services:
  - type: web
    name: yumgo-app
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: "./start.sh"
    autoDeploy: true