services:
  - type: web
    name: yumgo-app
    env: python
    plan: free

    buildCommand: |
      # Устанавливаем Rust для сборки зависимостей, которые используют pydantic-core / maturin
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      source $HOME/.cargo/env

      # Обновляем pip
      pip install --upgrade pip

      # Устанавливаем зависимости
      pip install -r requirements.txt

    startCommand: "./start.sh"
    autoDeploy: true